### ISSUE TITLE
add provider, manager, support nested macros

### ISSUE THREAD

**Issue by unbyte** [viteland/vite-plugin-macro#4]
## Roadmap

- [x] collect all macros into one transformer, i.e. register all macros into one global instance of vite-plugin-macro 
    #5
- [x] provide `containsMacros()` to check if there is unexpanded macro in args ~~, and `findMacro()` to find other macros.~~
    #6 
- [x] should copy some options like `parserPlugins` from plugin to manager.
    #9 
- [x] should improve the macro search mechanism.
    #12 
- [x] documentation.
    #17
